// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXfV6PgrJyeK6uwYwxSC-F4KU-jXXdUdQ',
    appId: '1:75037196994:web:9610f7aab22e261d2c715b',
    messagingSenderId: '75037196994',
    projectId: 'fir-memo-app-d448a',
    authDomain: 'fir-memo-app-d448a.firebaseapp.com',
    storageBucket: 'fir-memo-app-d448a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnJI8Ff2PAKVg5zbcOVuqCiJyxUsy-g0A',
    appId: '1:75037196994:android:5209eec173459d202c715b',
    messagingSenderId: '75037196994',
    projectId: 'fir-memo-app-d448a',
    storageBucket: 'fir-memo-app-d448a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBekgIwgz5lSqTfU_hiS-e3ZD6R6yz96QE',
    appId: '1:75037196994:ios:39c31b10cf267fc92c715b',
    messagingSenderId: '75037196994',
    projectId: 'fir-memo-app-d448a',
    storageBucket: 'fir-memo-app-d448a.appspot.com',
    iosClientId: '75037196994-6pvsldcanmcfs9hd48l13ck7tjq7f9ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBekgIwgz5lSqTfU_hiS-e3ZD6R6yz96QE',
    appId: '1:75037196994:ios:39c31b10cf267fc92c715b',
    messagingSenderId: '75037196994',
    projectId: 'fir-memo-app-d448a',
    storageBucket: 'fir-memo-app-d448a.appspot.com',
    iosClientId: '75037196994-6pvsldcanmcfs9hd48l13ck7tjq7f9ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTraining',
  );
}
